apiVersion: v1
kind: Pod 
metadata:
  name: my-web-app
  labels:
    app: dp 

spec:
  containers: 
    - name: my-nginx-app 
      image: mariammousa/nginx-os
      ports:
        - containerPort: 80 